// app/api/profile/gallery/route.ts

import { NextRequest, NextResponse } from 'next/server';
import { getUserFromToken } from '@/lib/auth';
import clientPromise from '@/lib/mongodb';
import { ObjectId } from 'mongodb';

// --- (1) DEFINE STRICT VALIDATION CONSTANTS ---
// Whitelist of allowed image MIME types. This prevents scriptable files like SVGs.
const ALLOWED_FILE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];
const MAX_FILE_SIZE_MB = 8;
const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;


/**
 * Uploads a file to the Cloudflare R2 gallery bucket via the worker. (No changes needed here)
 */
async function uploadToCloudflareR2(file: File, username: string): Promise<string> {
  const fileExtension = (file.name.split('.').pop() || 'png').toLowerCase();
  const key = `gallery/${username}/${Date.now()}.${fileExtension}`;
  const arrayBuffer = await file.arrayBuffer();
  const uploadUrl = `${process.env.R2_WORKER_UPLOAD_URL}?key=${encodeURIComponent(key)}&type=gallery`;

  const res = await fetch(uploadUrl, {
    method: 'PUT',
    headers: { 'Content-Type': file.type },
    body: arrayBuffer,
  });

  if (!res.ok) {
    const body = await res.text();
    console.error('R2 upload failed:', body);
    throw new Error('Failed to upload file to storage bucket.');
  }
  return key;
}


/**
 * Handles POST requests to upload a new gallery photo.
 */
export async function POST(request: NextRequest) {
  try {
    const user = await getUserFromToken(request);
    if (!user || !user.isProUser) {
      return NextResponse.json({ error: 'This feature is for Pro members only.' }, { status: 403 });
    }

    const formData = await request.formData();
    const file = formData.get('photo') as File | null;

    if (!file) {
        return NextResponse.json({ error: 'No photo provided.' }, { status: 400 });
    }

    // --- (2) HARDENED FILE VALIDATION ---
    // Check against the strict whitelist of MIME types.
    if (!ALLOWED_FILE_TYPES.includes(file.type)) {
        return NextResponse.json({ error: 'Invalid file type. Only JPG, PNG, GIF, and WEBP are allowed.' }, { status: 400 });
    }
    // Check against the defined max file size.
    if (file.size > MAX_FILE_SIZE_BYTES) {
        return NextResponse.json({ error: `File size must be less than ${MAX_FILE_SIZE_MB}MB.` }, { status: 400 });
    }


    const photoKey = await uploadToCloudflareR2(file, user.username);
    const client = await clientPromise;
    const db = client.db('whatsyourinfo');

    const newGalleryItem = {
      _id: new ObjectId(),
      key: photoKey,
      caption: '',
    };

    await db.collection('users').updateOne(
      { _id: new ObjectId(user._id) },
      { $push: { gallery: newGalleryItem } }
    );

    const publicUrl = `${process.env.R2_PUBLIC_URL}/${photoKey}`;
    
    return NextResponse.json({
      message: 'Photo uploaded successfully',
      item: { ...newGalleryItem, url: publicUrl },
    }, { status: 201 });

  } catch (error) {
    console.error('Gallery upload error:', error);
    return NextResponse.json({ error: 'Failed to upload photo.' }, { status: 500 });
  }
}


/**
 * Handles GET requests to fetch all gallery photos for the logged-in user. (This is already secure)
 */
export async function GET(request: NextRequest) {
  try {
    const user = await getUserFromToken(request);
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const client = await clientPromise;
    const db = client.db('whatsyourinfo');

    // Fetching data owned by the authenticated user is a secure pattern.
    const userData = await db.collection('users').findOne(
      { _id: new ObjectId(user._id) },
      { projection: { gallery: 1 } }
    );

    // The 'item.key' was generated by the server, so it's safe to use here.
    const galleryItems = (userData?.gallery || []).map(item => ({
      ...item,
      url: `${process.env.R2_PUBLIC_URL}/${item.key}`,
    }));

    return NextResponse.json({ items: galleryItems });

  } catch (error) {
    console.error('Fetch gallery error:', error);
    return NextResponse.json({ error: 'Failed to fetch gallery.' }, { status: 500 });
  }
}